name: chainlink-ftw
run-name: ${{ github.actor }} is preparing for the ChainLink interview
on: [push]
jobs:
  prepartion:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Preparation"
    
  prevents:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Prevents"
    needs: preparation
  poor:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Poor"
    needs: prevents
  performance:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Performance"
    needs: preparation